#!/usr/bin/env python3
"""Regenerate Tables 1-5, Figures 1-3 and supporting outputs in a new directory.

Published artifacts/ and all source directories are protected. This program calls
existing example scripts; their scientific calculations and checks are unchanged.
"""
from __future__ import annotations
import argparse
import csv
import hashlib
import json
from pathlib import Path
import subprocess
import sys

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / 'examples'))
from _common import prepare_out, run_script, write_json

REPO = 'https://github.com/TaylorResearchLab/biological-information-limit-1'
EXAMPLES = (
    ('01_tcell_proofreading', 'T cell receptor proofreading', 'run_tcell_proofreading.py',
     ('table_1_tcell_proofreading.csv',), 'figure_1_tcell_proofreading.png', ()),
    ('02_ribosome_selection', 'Ribosomal tRNA selection', 'run_ribosome_selection.py',
     ('table_2_ribosome_information.csv', 'table_3_ribosome_passage.csv'),
     'figure_2_ribosome_selection.png', ()),
    ('03_msn2_reporters', 'Yeast Msn2 reporters', 'run_msn2_reporters.py',
     ('table_4_msn2_information.csv', 'table_5_msn2_pairing.csv'),
     'figure_3_msn2_information.png', ('--full-derived',)),
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_records() -> dict[str, str]:
    """Identify calculation programs, required inputs and reference checks, not outputs."""
    paths = [ROOT / 'generate_artifacts.py', ROOT / 'requirements.txt', ROOT / 'verify_archive.py']
    for name in ('examples', 'workstreams', 'tools', 'provenance', 'reference_results'):
        paths.extend(p for p in (ROOT / name).rglob('*') if p.is_file()
                     and '__pycache__' not in p.parts and p.suffix != '.pyc')
    return {p.relative_to(ROOT).as_posix(): sha256(p) for p in sorted(set(paths))}


def display_value(key: str, value: str) -> str:
    if key == 'comparison':
        return value.replace('|', ' / ').replace('_', ' ')
    try:
        number = float(value)
    except ValueError:
        return value.replace('|', '\\|')
    if key == 'agonist_self_completion_ratio':
        return f'{number:.0e}'
    if key in ('proofreading_steps', 'pairing_sustained_retained', 'pairing_pulsed_retained'):
        return str(int(number))
    return f'{number:.3g}' if 0 < abs(number) < .01 else f'{number:.3f}'


def csv_preview(path: Path) -> str:
    with path.open(encoding='utf-8', newline='') as handle:
        reader = csv.DictReader(handle)
        fields = reader.fieldnames
        rows = list(reader)
    if not fields or not rows:
        raise ValueError(f'No table data: {path}')
    lines = ['| ' + ' | '.join(f.replace('_', ' ') for f in fields) + ' |',
             '| ' + ' | '.join('---' for _ in fields) + ' |']
    lines.extend('| ' + ' | '.join(display_value(f, r[f]) for f in fields) + ' |' for r in rows)
    return '\n'.join(lines)


def write_index(out: Path) -> None:
    overview = ['# Published results', '',
        'Tables, figures and supporting outputs generated by `generate_artifacts.py` from the included data.', '',
        '| Example | Saved tables and figure | Script |', '| --- | --- | --- |']
    for directory, title, script, tables, figure, _ in EXAMPLES:
        overview.append(f'| {title} | [View results]({directory}/) | '
                        f'[{script}]({REPO}/blob/main/examples/{directory}/{script}) |')
        folder = out / directory
        lines = [f'# {title}', '', f'[Script and explanation]({REPO}/tree/main/examples/{directory})', '',
                 f'![Generated figure]({figure})', '',
                 'The CSV files retain full numerical precision. The previews below are rounded for reading.', '']
        for name in tables:
            lines += [f'## Table {name.split("_")[1]}', '', f'[Full precision CSV]({name})', '',
                      csv_preview(folder / name), '']
        lines += ['## Supporting outputs', '',
                  'The figure reads the calculated CSV tables. `figure_data.json` records the plotted rows and their hashes.', '',
                  '[Parameters used](parameters_used.json) and [verification record](verification.json).', '',
                  'Other CSV and JSON files in this directory contain the accompanying calculations. '
                  'The verification record identifies every source file checked and output produced.', '']
        (folder / 'README.md').write_text('\n'.join(lines), encoding='utf-8')
    overview += ['', '## Regenerate without changing these files', '',
        'From the repository folder after installing `requirements.txt`:', '', '```bash',
        'python generate_artifacts.py --out runs/my_artifacts', '```', '',
        'An absolute path to a new folder outside the repository also works. Quote paths containing spaces. '
        'Existing nonempty folders are refused. All repository directories except new folders beneath `runs/` are protected.', '',
        'The generated folder has the same example directories as this one. Compare the CSV tables and figures directly. '
        'Each example also runs its existing numerical checks. No separate comparison command is required.', '',
        'Scientific CSV/JSON results are reproducible. Log paths, runtime and environment records depend on the run. '
        'Image bytes can differ with plotting-library or font versions even when the plotted data agree. '
        '`figure_data.json` gives the numerical figure inputs.', '',
        'The generated PNGs are renderings from recalculated results. They are not asserted to be pixel-identical '
        'to figure images embedded in an earlier manuscript draft.', '',
        '## Scope', '',
        'All five main tables and three main figures are regenerated. The Msn2 example starts from included binary counts '
        'and also verifies all 1,360 comparisons from the saved scalar features. Original fluorescence smoothing and '
        'feature extraction remain a separate source-data procedure described in the repository documentation.', '',
        'These are numerical reproduction records, not population confidence intervals or independent biological replication.', '',
        '## Provenance', '',
        '`artifact_manifest.json` records the generating source revision, source hashes and output hashes. '
        'It excludes its own hash. This snapshot is kept on main; normal runs never replace it.', '']
    (out / 'README.md').write_text('\n'.join(overview), encoding='utf-8')


def validate_bundle(out: Path) -> dict:
    """Check a bundle's inventory, hashes and passed example records, without altering it."""
    out = out.resolve()
    manifest = json.loads((out / 'artifact_manifest.json').read_text())
    if manifest.get('status') != 'PASS':
        raise AssertionError('Artifact bundle is not marked PASS')
    expected = manifest['files']
    actual = {p.relative_to(out).as_posix() for p in out.rglob('*') if p.is_file()
              and p != out / 'artifact_manifest.json'}
    if actual != set(expected):
        raise AssertionError('Artifact inventory differs from manifest')
    for name, record in expected.items():
        p = out / name
        if p.is_symlink() or not p.resolve().is_relative_to(out):
            raise AssertionError(f'Unsafe artifact path: {name}')
        if p.stat().st_size != record['bytes'] or sha256(p) != record['sha256']:
            raise AssertionError(f'Artifact bytes changed: {name}')
    for directory, _, _, tables, figure, _ in EXAMPLES:
        report = json.loads((out / directory / 'verification.json').read_text())
        if report.get('status') != 'PASS':
            raise AssertionError(f'Example verification failed: {directory}')
        for name in tables:
            if not (out / directory / name).is_file():
                raise AssertionError(f'Missing table: {name}')
        if (out / directory / figure).read_bytes()[:8] != b'\x89PNG\r\n\x1a\n':
            raise AssertionError(f'Invalid PNG: {figure}')
        plotted = json.loads((out / directory / 'figure_data.json').read_text())
        for name, record in plotted['inputs'].items():
            if sha256(out / directory / name) != record['sha256']:
                raise AssertionError(f'Figure input differs: {name}')
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', type=Path, default=ROOT / 'runs' / 'all_artifacts',
                        help='New output directory. Default: runs/all_artifacts. Published artifacts are protected.')
    args = parser.parse_args()
    out = prepare_out(args.out)
    before = source_records()
    revision = None
    if (ROOT / '.git').exists():
        result = subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=ROOT, capture_output=True, text=True)
        if result.returncode == 0:
            revision = result.stdout.strip()
    for directory, title, script, _, _, extra in EXAMPLES:
        print(f'Running {title}', flush=True)
        run_script(ROOT / 'examples' / directory / script,
                   ['--out', str(out / directory), *extra], out / f'{directory}.log')
        report = json.loads((out / directory / 'verification.json').read_text())
        if report.get('status') != 'PASS':
            raise AssertionError(f'{title} did not pass')
    if source_records() != before:
        raise AssertionError('A source or reference file changed during the run')
    write_index(out)
    files = {p.relative_to(out).as_posix(): {'bytes': p.stat().st_size, 'sha256': sha256(p)}
             for p in sorted(out.rglob('*')) if p.is_file()}
    write_json(out / 'artifact_manifest.json', {'status': 'PASS', 'format_version': 1,
        'source_commit': revision, 'source_sha256': before,
        'tables': 5, 'figures': 3, 'msn2_full_derived_verification': True,
        'files': files})
    validate_bundle(out)
    print(f'PASS. Five tables, three figures and supporting outputs saved in {out}')


if __name__ == '__main__':
    try:
        main()
    except (OSError, ValueError, AssertionError, RuntimeError) as exc:
        print(f'ERROR: {exc}', file=sys.stderr)
        raise SystemExit(1) from exc
